"use client"
// import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { CookiesProvider } from "react-cookie";
import Head from "next/head";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Flow your mind</title>
        <meta name="theme-color" content="#1b1871f"/>
      </Head>
      <body>
        <Toaster
          position={"top-center"}
          reverseOrder={false}
          toastOptions={{
            // Define default options
            className: "",
            style: {
              margin: "40px",
              background: "#363636",
              // background: "#00e676",
              color: "#fff",
              zIndex: 1,
              // width: "28vh",
            },
            duration: 5000,
            // Default options for specific types
            success: {
              duration: 8000,
            },
            error: {
              style: {
                background: "#f44336",
              },
              duration: 8000,
            },
          }}
        />
        <CookiesProvider>
          {children}
        </CookiesProvider>
      </body>
    </html>
  );
}
